Repository B1ime/client, pull requests merged in 2018-10, with the labels that each got.

#3 #1 - ESLint 설정
  .eslintrc.js
  package-lock.json
  package.json
Labels: enhancement, 프론트, 환경설정

#4 #2 - Add redux integration
  README.md
  package.json
  src/actions/actionTypes.js
  src/actions/actions.js
  src/reducers/index.js
  src/stores/index.js
  yarn.lock
Labels: enhancement, 프론트, 환경설정

#5 Develop
  .eslintrc.js
  .gitignore
  README.md
  package-lock.json
  package.json
  src/actions/actionTypes.js
  src/actions/actions.js
  src/reducers/index.js
  src/stores/index.js
  yarn.lock
Labels: 프론트

#9 Feature/issue 0007
  .eslintrc.js
  package.json
  src/components/App.js
  src/components/Banner.js
  src/components/ColorPicker.js
  src/components/Components.css
  src/components/Footer.js
  src/components/Form.js
  src/components/Map.js
  src/components/Member.js
  src/components/Navbar.js
  src/components/NavbarForCreate.js
  src/components/NewRoom.js
  src/components/Room.js
  src/components/index.js
  src/components/pages/Login.js
  src/components/pages/Main.js
  src/components/pages/Pages.css
  src/components/pages/RoomCreate.js
  src/components/pages/RoomDetail.js
  src/components/pages/RoomList.js
  src/components/pages/index.js
  src/images/back.png
  src/images/cancel.png
  src/images/makeroom.png
  src/images/participate.png
  src/images/plus.png
  src/images/profile.png
  src/images/reload.png
  src/index.css
  src/index.js
  yarn.lock
Labels: enhancement, 새로운 기능, 프론트

#12 Feature/issue 0008
  .eslintrc.js
  .prettierrc
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/actions/login/actionTypes.js
  src/actions/login/actions.js
  src/components/atoms/Paragraph.js
  src/components/atoms/Title.js
  src/components/atoms/index.js
  src/components/molecules/LoginElement.js
  src/components/molecules/index.js
  src/components/organisms/AppIcon.png
  src/components/organisms/AppLabel.js
  src/components/organisms/Footer.js
  src/components/organisms/GoogleLogin.png
  src/components/organisms/IntroSection.js
  src/components/organisms/KakaoLogin.png
  src/components/organisms/LoginSection.js
  src/components/organisms/index.js
  src/components/pages/Login.js
  src/components/pages/Main.js
  src/components/templates/LoginLayout.js
  src/components/templates/MainLayout.js
  src/components/templates/index.js
  src/index.css
  src/index.js
  src/reducers/index.js
  src/reducers/loginReducer.js
  src/stores/index.js
  yarn.lock
Labels: enhancement, 새로운 기능, 프론트
